server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                      #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routth1                #payment_route : 路由的ID，没有固定规则，要求唯一，建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getById/**       #断言，路径相匹配的跳转路由
            #- After=2022-06-05T11:36:33.289+08:00[Asia/Shanghai]
            #- Cookie=username,yyzz
            #- Header=X-Request-Id, \d+       #断言，必须携带X-Request-Id请求头，值必须为数字
            #- Host=*.caoliang.com,*.cl.org
            - Query=username, \d+             # 要有参数名username并且值还要是整数才能通过路由

        - id: payment_routth2                #payment_route : 路由的ID，没有固定规则，要求唯一，建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**            #断言，路径相匹配的跳转路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
