server:
  port: ${port:7001}

eureka:
  instance:
    hostname: eureka-server #eureka服务端的实例名称
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false       #false表示自己就是注册中心，职责是维护服务实例，不需要检索服务
    service-url:
      defaultZone: ${defaultZone:http://127.0.0.1:7002/eureka/}    #设置于Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
