server:
  port: ${port:7001}

eureka:
  instance:
    hostname: eureka-server #eureka服务端的实例名称
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false       #false表示自己就是注册中心，职责是维护服务实例，不需要检索服务
    service-url:
      #集群方式：指向其他eureka
      #defaultZone: ${defaultZone:http://127.0.0.1:7002/eureka/}    #设置于Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #单机方式：指向自己
      defaultZone: http://127.0.0.1:7001/eureka/
#  server:
#    enable-self-preservation: false #关闭自我保护
#    eviction-interval-timer-in-ms: 6000 #服务失效剔除时间间隔，默认60000ms
